# contains other services that the application needs to run with
version: '3.1'

services:
  db:
    # keep the postgres version in sync with the version in deployment
    image: postgres:15
    restart: always
    environment:
      # forward the environment variables to the postgres container
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      # 5432 is the default port for postgres
      - ${DATABASE_PORT}:5432