version: '3.1'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: user
      POSTGRES_USER: password
      POSTGRES_DB: homefinder
    ports:
      - 5432:5432