INSERT INTO
    home (
        title,
        price,
        address,
        rooms,
        sqm_living_space,
        sqm_property_space,
        bedrooms,
        bathrooms,
        details,
        original_source,
        source_url,
        first_fetch_date,
        last_fetch_date,
        created_at,
        updated_at
    )
VALUES
    (
        'Gemütliches Stadthaus in zentraler Lage',
        450000,
        'Berlin',
        3,
        120,
        250,
        2,
        1,
        'Kamin, Balkon mit Blick auf den Park',
        '<html> ....</html>',
        'https://example.com/listing/456',
        '2022-01-02',
        '2022-02-06',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'Luxuriöse Villa am See',
        1500000,
        'Munich',
        6,
        300,
        600,
        4,
        3,
        'Swimmingpool, Sauna, Garten',
        '<html> ....</html>',
        'https://example.com/listing/789',
        '2022-01-03',
        '2022-02-07',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'Moderne Wohnung in der Innenstadt',
        300000,
        'Hamburg',
        2,
        80,
        100,
        1,
        1,
        'Balkon, Aufzug',
        '<html> ....</html>',
        'https://example.com/listing/123',
        '2022-01-04',
        '2022-02-08',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'Einfamilienhaus im Grünen',
        500000,
        'Cologne',
        4,
        150,
        300,
        3,
        2,
        'Garten, Garage',
        '<html> ....</html>',
        'https://example.com/listing/987',
        '2022-01-05',
        '2022-02-09',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'Gemütliche Dachgeschosswohnung',
        200000,
        'Frankfurt',
        3,
        90,
        120,
        2,
        1,
        'Einbauküche, Balkon',
        '<html> ....</html>',
        'https://example.com/listing/654',
        '2022-01-06',
        '2022-02-10',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'Großes Einfamilienhaus mit Garten',
        800000,
        'Stuttgart',
        5,
        200,
        400,
        4,
        3,
        'Kamin, Terrasse',
        '<html> ....</html>',
        'https://example.com/listing/321',
        '2022-01-07',
        '2022-02-11',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'Stilvolle Altbauwohnung',
        400000,
        'Dresden',
        4,
        120,
        150,
        3,
        2,
        'Parkettboden, Stuckdecken',
        '<html> ....</html>',
        'https://example.com/listing/789',
        '2022-01-08',
        '2022-02-12',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'Modernes Loft in angesagtem Viertel',
        600000,
        'Hannover',
        3,
        150,
        200,
        2,
        2,
        'Offene Küche, Balkon',
        '<html> ....</html>',
        'https://example.com/listing/234',
        '2022-01-09',
        '2022-02-13',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'Charmantes Reihenhaus mit Garten',
        350000,
        'Leipzig',
        4,
        100,
        200,
        3,
        2,
        'Einbauküche, Terrasse',
        '<html> ....</html>',
        'https://example.com/listing/567',
        '2022-01-10',
        '2022-02-14',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'Großzügige Penthouse-Wohnung',
        900000,
        'Düsseldorf',
        5,
        180,
        250,
        4,
        3,
        'Dachterrasse, Aufzug',
        '<html> ....</html>',
        'https://example.com/listing/876',
        '2022-01-11',
        '2022-02-15',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    );